/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cipherproject;

import cipherproject.Classes.CipherTextEditor;

public class App {
    public String getGreeting() {
        return "Hello world!";
    }

    public static void main(String[] args) {
        new CipherTextEditor();
        /*TextEditor textEditor = */
        //Cipher cipherText = new Cipher("abcd");
    }
}
