/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cipherproject;

import cipherproject.Classes.Cipher;
import cipherproject.Classes.CipherTextEditor;

public class App {
    
    /** 
     * Greeting traveler
     * @return 
     * Hello world!
     */
    public String getGreeting() {
        return "Hello world!";
    }
    
    public static void main(String[] args) {
        new CipherTextEditor();
    }
}
